#!/usr/bin/env python3
"""
setup_dev.py — One-time development environment setup.
======================================================
Run this ONCE from the project root to generate cryptographically-secure
tokens for every agent and write them to .env:

    python3 setup_dev.py

After running, start the server:

    python3 RISHI.py

Then in a second terminal, run the orchestrator:

    cd agents/chanakya && python3 orchestrator.py

Both processes automatically load .env via python-dotenv.
"""

import os
import secrets

ROOT = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(ROOT, ".env")

AGENT_IDS = [
    "RISHI_CORE_NODE",
    "AGENT_CHANAKYA_DETERMINISTIC",
    "AGENT_CHANAKYA_AUDITABILITY",
    "AGENT_CHANAKYA_ETHICAL",
    "AGENT_CHANAKYA_CRITICAL",
    "AGENT_CHANAKYA_COMMUNICATION",
    "AGENT_CHANAKYA_VISUALIZATION",
    "AGENT_CHANAKYA_ESG",
    "AGENT_CHANAKYA_ADAPTABILITY",
    # Engineer sub-agents
    "AGENT_ENGINEER_CODER",
    "AGENT_ENGINEER_DESIGNER",
    "AGENT_ENGINEER_GENERATIVE",
]


def main():
    print("=" * 56)
    print("  CloseAI Dev Environment Setup")
    print("=" * 56)

    # Preserve any existing non-token lines (comments, custom vars)
    existing_lines = []
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                stripped = line.strip()
                # Keep comment lines and non-token vars, skip old token lines
                is_token_line = any(
                    stripped.startswith(f"AGENT_TOKEN_{a}") for a in AGENT_IDS
                )
                is_critical_ram = stripped.startswith("CRITICAL_RAM_PERCENT")
                if not is_token_line and not is_critical_ram:
                    existing_lines.append(line)

    token_lines = []
    print("\nGenerating tokens:")
    for agent_id in AGENT_IDS:
        token = secrets.token_hex(32)
        key = f"AGENT_TOKEN_{agent_id}"
        token_lines.append(f"{key}={token}\n")
        print(f"  ✅  {key}")

    # RAM threshold — raised for Ollama's memory footprint
    token_lines.append("CRITICAL_RAM_PERCENT=92.0\n")

    with open(ENV_FILE, "w") as f:
        f.writelines(existing_lines)
        f.write("\n# === Auto-generated by setup_dev.py — do not edit manually ===\n")
        f.writelines(token_lines)

    print(f"\n✅  Tokens written to {ENV_FILE}")
    print("\nNext steps:")
    print("  1.  python3 RISHI.py                              (terminal 1)")
    print("  2.  cd agents/chanakya && python3 orchestrator.py  (terminal 2)")
    print("  3.  cd agents/kavach   && python3 orchestrator.py  (terminal 3, optional)")
    print("  4.  cd agents/engineer && python3 orchestrator.py  (terminal 4, optional)")
    print("=" * 56)


if __name__ == "__main__":
    main()
